---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    component: queue-entry-operator-dev
  name: queue-entry-operator-dev
  namespace: queo
spec:
  replicas: 1
  selector:
    matchLabels:
      component: queue-entry-operator-dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: queue-entry-operator-dev
    spec:
      containers:
      - image: gonna-have-to-build-it-yourself.for.now/k8s-queue-entry-operator:0.1.0
        env:
        - name: K8S_QUEUE_ENTRY_OPERATOR_SCOPE
          value: dev
        name: queue-entry-operator
        resources:
          limits:
            memory: 128M
      securityContext:
        runAsNonRoot: true
      serviceAccountName: queue-entry-operator

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: queue-entry-operator
  namespace: queo

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: queue-entry-operator
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - list
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - "queueentryoperator.evanzeimet.com"
  resources:
  - "*"
  verbs:
  - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: queue-entry-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: queue-entry-operator
subjects:
- kind: ServiceAccount
  name: queue-entry-operator
  namespace: queo
